defaults:
  - env: default
  - log: default
  - hydra: default

output: /grogu/user/pmorgado/workspace/slurm_example
exp_name: cifar10_resnet18
worker: train_cifar

arch: resnet18
pretrained: true

epochs: 100
start_epoch: 0
batch_size: 256
lr: 0.1
momentum: 0.9
weight_decay: 5e-4

resume: True
evaluate: False
seed: -1